id: I86285406
ocr_import_info:
  timestamp: '2023-09-25T16:18:49.706188+00:00'
  batch_id: batch-79a6
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-25 16:26:34.726487+00:00
last_modified: 2023-09-25 16:26:34.726494+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG15933
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG15933
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་འཇུག་པའི་རྣམ་བཤད་རབ་གསལ་འོད་སྣང་གསར་པ།
  languages:
  - bo
  author: མཁན་པོ་ཚེ་དབང་བསོད་ནམས།
statistics:
  ocr_word_mean_confidence_index: 0.9981953388766015
  ocr_word_median_confidence_index: 1.0
bases:
  I1KG15956:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15956
      total_pages: 536
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG15956.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9981953388766015
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
